name: CMake

on: [ push, pull_request, workflow_dispatch ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v2

      - uses: lukka/run-vcpkg@v11

      - uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{github.workspace}}/CMakeLists.txt'
